import type { Metadata } from "next";
import { Jost
} from "next/font/google";
import "./globals.scss";
import { readFilesFromDir } from "./get_sub_folders";
import Paths from "./Paths";
const robto = Jost({ 	weight: [ "400","100","700"],
	subsets: ["latin-ext"],
	display: 'swap'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default async function RootLayout({
// 	children,
// }: {
// 	children: React.ReactNode;
// }) {
// 	const files = (await readFilesFromDir(`./src/app/verkefni/vel608g`))
// 	return (<>
// 		<Paths files={files} image="/spil/joker.svg" />
// 		{children}
// 	</>
// 	);
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
		const files = (await readFilesFromDir(`./src/app/`))
  return (
    <html lang="en">
      <body className={robto.className}>
	  <header>
		<div>
			<h1>HÍ textíll</h1>
			<p>Nettengdar prjónar vélar</p>
		</div>
			<Paths files={files} depth={1}/>
		</header>
		{children}</body>
    </html>
  );
}

